//
//  LocalPhoneString.swift
//  Delius
//
//  Created by 박진호 on 2020/06/21.
//  Copyright © 2020 정윤환. All rights reserved.
//

import UIKit
class LocalPhoneString{
    class func localPhonePickerArray()->[String]{
        let Guatemala = "Guatemala"
        let Greece = "Greece"
        let Netherlands = "Netherlands"
        let Norway = "Norway"
        let NewZealand = "NewZealand"
        let Taiwan = "Taiwan"
        let RepublicOfKorea = "Republic Of Korea"
        let Denmark = "Denmark"
        let Germany = "Germany"
        let Latvia = "Latvia"
        let Russia = "Russia"
        let Romania = "Romania"
        let Loxembourg = "Loxembourg"
        let Lithuania = "Lithuania"
        let Liechtenstein = "Liechtenstein"
        let Macau = "Macau"
        let Malaysia = "Malaysia"
        let Mexico = "Mexico"
        let Morocco = "Morocco"
        let UnitedStatesOfAmerica = " United States Of America"
        let Myanmar = "Myanmar"
        let Bangladesh = "Bangladesh"
        let Venezuela = "Venezuela"
        let Vietnam = "Vietnam"
        let Belgium = "Belgium"
        let Belarus = "Belarus"
        let Bolivia = "Bolivia"
        let Bulgaria = "Bulgaria"
        let Brazil = "Brazil"
        let Serbia = "Serbia"
        let SriLanka = "SriLanka"
        let Swedan = "Swedan"
        let Switzerland = "Switzerland"
        let Spain = "Spain"
        let Slovakia = "Slovakia"
        let Slovenia = "Slovenia"
        let Singapore = "Singapore"
        let Armenia = "Armenia"
        let Argentina = "Argentina"
        let Iceland = "Iceland"
        let Haiti = "Haiti"
        let Ireland = "Ireland"
        let Estonia = "Estonia"
        let Ecuador = "Ecuador"
        let UnitedKingdom = "United Kingdom"
        let Austria = "Austria"
        let Honduras = "Honduras"
        let Uruguay = "Uruguay"
        let Uzbekistan = "Uzbekistan"
        let Ukrine = "Ukrine"
        let Italy = "Italy"
        let Japan = "Japan"
        let China = "China"
        let CzechRepublic = "CzechRepublic"
        let Chile = "Chile"
        let Cambodia = "Cambodia"
        let Canada = "Canada"
        let Colombia = "Colombia"
        let Croatia = "Croatia"
        let Thailand = "Thailand"
        let Panama = "Panama"
        let Paraguay = "Paraguay "
        let PapuaNewGuinea = "PapuaNewGuinea"
        let Peru = "Peru"
        let Portugal = "Portugal"
        let Poland = "Poland"
        let France = "France"
        let Finland = "Finland"
        let Philippines = "Philippines"
        let Hungary = "Hungary"
        let HongKong = "HongKong"
        return [Guatemala,Greece,Netherlands,Norway,NewZealand,Taiwan,RepublicOfKorea,Denmark,Germany,Latvia,Russia,Romania,Loxembourg,Lithuania,Liechtenstein,Macau,Malaysia,Mexico,Morocco,UnitedStatesOfAmerica,Myanmar,Bangladesh,Venezuela,Vietnam,Belgium,Belarus,Bolivia,Bulgaria,Brazil,Serbia,SriLanka,Swedan,Switzerland,Spain,Slovakia,Slovenia,Singapore,Armenia,Argentina,Iceland,Haiti,Ireland,Estonia,Ecuador,UnitedKingdom,Austria,Honduras,Uruguay,Uzbekistan,Ukrine,Italy,Japan,China,CzechRepublic,Chile,Cambodia,Canada,Colombia,Croatia,Thailand,Panama,Paraguay,PapuaNewGuinea,Peru,Portugal,Poland,France,Finland,Philippines,Hungary,HongKong]
    }
    class func localPhoneArray()->[String]{
        let Guatemala = "+502"
        let Greece = "+30"
        let Netherlands = "+31"
        let Norway = "+47"
        let NewZealand = "+64"
        let Taiwan = "+886"
        let RepublicOfKorea = "+82"
        let Denmark = "+45"
        let Germany = "+49"
        let Latvia = "+371"
        let Russia = "+7"
        let Romania = "+40"
        let Loxembourg = "+352"
        let Lithuania = "+370"
        let Liechtenstein = "+423"
        let Macau = "+853"
        let Malaysia = "+60"
        let Mexico = "+52"
        let Morocco = "+212"
        let UnitedStatesOfAmerica = "+1"
        let Myanmar = "+95"
        let Bangladesh = "+880"
        let Venezuela = "+58"
        let Vietnam = "+84"
        let Belgium = "+32"
        let Belarus = "+375"
        let Bolivia = "+591"
        let Bulgaria = "+359"
        let Brazil = "+55"
        let Serbia = "+381"
        let SriLanka = "+94"
        let Swedan = "+46"
        let Switzerland = "+41"
        let Spain = "+34"
        let Slovakia = "+421"
        let Slovenia = "+386"
        let Singapore = "+65"
        let Armenia = "+374"
        let Argentina = "+54"
        let Iceland = "+354"
        let Haiti = "+509"
        let Ireland = "+353"
        let Estonia = "+372"
        let Ecuador = "+593"
        let UnitedKingdom = "+44"
        let Austria = "+43"
        let Honduras = "+504"
        let Uruguay = "+598"
        let Uzbekistan = "+998"
        let Ukrine = "+380"
        let Italy = "+39"
        let Japan = "+81"
        let China = "+86"
        let CzechRepublic = "+420"
        let Chile = "+56"
        let Cambodia = "+855"
        let Canada = "+1"
        let Colombia = "+57"
        let Croatia = "+385"
        let Thailand = "+66"
        let Panama = "+507"
        let Paraguay = "+595"
        let PapuaNewGuinea = "+675"
        let Peru = "+51"
        let Portugal = "+351"
        let Poland = "+48"
        let France = "+33"
        let Finland = "358"
        let Philippines = "+63"
        let Hungary = "+36"
        let HongKong = "+852"
        return [Guatemala,Greece,Netherlands,Norway,NewZealand,Taiwan,RepublicOfKorea,Denmark,Germany,Latvia,Russia,Romania,Loxembourg,Lithuania,Liechtenstein,Macau,Malaysia,Mexico,Morocco,UnitedStatesOfAmerica,Myanmar,Bangladesh,Venezuela,Vietnam,Belgium,Belarus,Bolivia,Bulgaria,Brazil,Serbia,SriLanka,Swedan,Switzerland,Spain,Slovakia,Slovenia,Singapore,Armenia,Argentina,Iceland,Haiti,Ireland,Estonia,Ecuador,UnitedKingdom,Austria,Honduras,Uruguay,Uzbekistan,Ukrine,Italy,Japan,China,CzechRepublic,Chile,Cambodia,Canada,Colombia,Croatia,Thailand,Panama,Paraguay,PapuaNewGuinea,Peru,Portugal,Poland,France,Finland,Philippines,Hungary,HongKong]
    }
    static var countryCode: [String:String] = ["BD": "880", "BE": "32", "BF": "226", "BG": "359", "BA": "387", "BB": "+1-246", "WF": "681", "BL": "590", "BM": "441", "BN": "673", "BO": "591", "BH": "973", "BI": "257", "BJ": "229", "BT": "975", "JM": "876", "BV": "", "BW": "267", "WS": "685", "BQ": "599", "BR": "55", "BS": "+242", "JE": "+44-1534", "BY": "375", "BZ": "501", "RU": "7", "RW": "250", "RS": "381", "TL": "670", "RE": "262", "TM": "993", "TJ": "992", "RO": "40", "TK": "690", "GW": "245", "GU": "+1-671", "GT": "502", "GS": "", "GR": "30", "GQ": "240", "GP": "590", "JP": "81", "GY": "592", "GG": "+44-1481", "GF": "594", "GE": "995", "GD": "+1-473", "GB": "44", "GA": "241", "SV": "503", "GN": "224", "GM": "220", "GL": "299", "GI": "350", "GH": "233", "OM": "968", "TN": "216", "JO": "962", "HR": "385", "HT": "509", "HU": "36", "HK": "852", "HN": "504", "HM": " ", "VE": "58", "PR": "+1-787 and 1-939", "PS": "970", "PW": "680", "PT": "351", "SJ": "47", "PY": "595", "IQ": "964", "PA": "507", "PF": "689", "PG": "675", "PE": "51", "PK": "92", "PH": "63", "PN": "870", "PL": "48", "PM": "508", "ZM": "260", "EH": "212", "EE": "372", "EG": "20", "ZA": "27", "EC": "593", "IT": "39", "VN": "84", "SB": "677", "ET": "251", "SO": "252", "ZW": "263", "SA": "966", "ES": "34", "ER": "291", "ME": "382", "MD": "373", "MG": "261", "MF": "590", "MA": "212", "MC": "377", "UZ": "998", "MM": "95", "ML": "223", "MO": "853", "MN": "976", "MH": "692", "MK": "389", "MU": "230", "MT": "356", "MW": "265", "MV": "960", "MQ": "596", "MP": "+1-670", "MS": "+1-664", "MR": "222", "IM": "+44-1624", "UG": "256", "TZ": "255", "MY": "60", "MX": "52", "IL": "972", "FR": "33", "IO": "246", "SH": "290", "FI": "358", "FJ": "679", "FK": "500", "FM": "691", "FO": "298", "NI": "505", "NL": "31", "NO": "47", "NA": "264", "VU": "678", "NC": "687", "NE": "227", "NF": "672", "NG": "234", "NZ": "64", "NP": "977", "NR": "674", "NU": "683", "CK": "682", "XK": "", "CI": "225", "CH": "41", "CO": "57", "CN": "86", "CM": "237", "CL": "56", "CC": "61", "CA": "1", "CG": "242", "CF": "236", "CD": "243", "CZ": "420", "CY": "357", "CX": "61", "CR": "506", "CW": "599", "CV": "238", "CU": "53", "SZ": "268", "SY": "963", "SX": "599", "KG": "996", "KE": "254", "SS": "211", "SR": "597", "KI": "686", "KH": "855", "KN": "+1-869", "KM": "269", "ST": "239", "SK": "421", "KR": "82", "SI": "386", "KP": "850", "KW": "965", "SN": "221", "SM": "378", "SL": "232", "SC": "248", "KZ": "7", "KY": "+1-345", "SG": "65", "SE": "46", "SD": "249", "DO": "+1-809", "DM": "+1-767", "DJ": "253", "DK": "45", "VG": "+1-284", "DE": "49", "YE": "967", "DZ": "213", "US": "1", "UY": "598", "YT": "262", "UM": "1", "LB": "961", "LC": "+1-758", "LA": "856", "TV": "688", "TW": "886", "TT": "+1-868", "TR": "90", "LK": "94", "LI": "423", "LV": "371", "TO": "676", "LT": "370", "LU": "352", "LR": "231", "LS": "266", "TH": "66", "TF": "", "TG": "228", "TD": "235", "TC": "+1-649", "LY": "218", "VA": "379", "VC": "+1-784", "AE": "971", "AD": "376", "AG": "+1-268", "AF": "93", "AI": "+1-264", "VI": "+1-340", "IS": "354", "IR": "98", "AM": "374", "AL": "355", "AO": "244", "AQ": "", "AS": "+1-684", "AR": "54", "AU": "61", "AT": "43", "AW": "297", "IN": "91", "AX": "+358-18", "AZ": "994", "IE": "353", "ID": "62", "UA": "380", "QA": "974", "MZ": "258"]
    
}
